# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
				  
    - name: Build with Maven # Este paso compila el código
      run: mvn -B compile --file pom.xml # Cambiado de 'package' a 'compile' para separar fases
                                        # Esto solo compila el código fuente principal.

    - name: Run Maven Tests # Nuevo paso: Ejecuta solo los tests
      run: mvn -B test --file pom.xml # Ejecuta los tests definidos en tu pom.xml

    - name: Package with Maven # Nuevo paso: Empaqueta el proyecto después de los tests
      run: mvn -B package --file pom.xml # Ahora sí, crea el JAR/WAR
